services:
  promodoro-web-dev:
    restart: always
    container_name: promodoro-web-dev
    image: promodoro-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@promodoro-db-dev:5432/db
      JWT_SECRET: test
    depends_on:
      - promodoro-db-dev

  promodoro-db-dev:
    restart: always
    container_name: promodoro-db-dev
    image: postgres:17.4-alpine3.21
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    user: "1000:1000"

volumes:
  node_modules:
    name: node_modules
