FROM node:22-alpine3.20 AS base

FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM base AS runner

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

CMD ["npm", "run", "dev"]
EXPOSE 3000
